# .travis.yml

language: haskell

sudo: required

before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install ghc-8.0.1
- sudo apt-get install cabal-install-1.24
- export PATH=/opt/cabal/1.24/bin:/opt/ghc/8.0.1/bin:$PATH
- cabal update

install:
# with cabal 1.24 and ghc 8.0.1, "--reorder-goals" is required for dependencies
# to successfully install (and the build is much slower than with
# ghc 7.10.3). TODO: track down problem sometime.
- cabal install --only-dependencies --enable-tests --enable-benchmarks --flags="enabletests" --force-reinstalls --reorder-goals

script:
- cabal configure --enable-tests --enable-benchmarks -v2 --flags="enabletests"
- cabal build
- cabal test --show-details=always
- cabal check
# check that the generated source-distribution can be built & installed
- cabal sdist
- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') 
- (cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi)
- echo pkg file is "`ls dist/$SRC_TGZ`"


deploy:
  file: dist/${SRC_TGZ}
  provider: releases
  skip_cleanup: true
  # overwrite: true
  api_key:
    secure: RzlHVrVLGvb8Or+PLzfdUF6YFIFU65xqZ3hl8TodglRnA8avcfej/W/K/aaXKb+i9eL4lmbc8WtTR5Qm8CxNtlR/uPAC1LBEVhJQHBKn6n1/uRTMOaRs75UjsIcm3GQKuOWI0HpMvb8Px7LBqdlE6wJURvqBTqkbomO6OMl8I2gMO0rYYP/ylf5e9Ozl0AzMWqzjwrA3brw6CTPWcup8s4GwHnsdisxrQDkE1ltt5P+MluJGKbQ4PDHrINOnUXSL/lcvUHc4i5clAqO7Baff0QCdl/RBxML5/fDB/OHuJpDu3GRXcWloQReu1gw3zuVaT9yA5JZvf4XQy2fnFNZUDbeNlM4L1tt19JOvLTzBPrr/KchxJ3aKW8L9z0dpMQ1sxE77VyJ+Bpg68k9pzBGcZ8XO0kraS1ZuAdP5LyuOnxOusG6vJA+MRSh+3kmeuOsqi0xVlrr89RiuIwFTG2fegDj5+PH6MTOnEJlfKHmK4pEB+NSSfVvmX8JBOlTg6v/HJpiMxGxpdkrvAC6Adb+gm1M6f5eZrPU3R0AFmDQ1me9HVCg2cL3l4lMgn88OUkRy79ipPPajLZ/CpE/+6j3Gau3XuZbg8LbH3Vo72KSeWaqPo9wge2/poeqfPYBvj+GGAR0GihAOJLvOldX1+VMQd6GWpTp16W2hA7XePxOIQkI=
  on:
    tags: true
    all_branches: true
    repo: phlummox/hup
