# .travis.yml

language: haskell

sudo: required

before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install ghc-8.0.1
- sudo apt-get install cabal-install-1.24
- export PATH=/opt/cabal/1.24/bin:/opt/ghc/8.0.1/bin:$PATH
- cabal update

install:
- cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
- cabal configure --enable-tests --enable-benchmarks -v2
#- echo `ls`
- cabal build
- cabal test
- cabal check
# check that the generated source-distribution can be built & installed
- cabal sdist
- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') 
- (cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi)
- echo pkg file is "`ls dist/$SRC_TGZ`"


before_deploy: 
- echo 'before deploy'
- echo pkg "dist/$SRC_TGZ"
- echo tag ${TRAVIS_TAG}
- echo branch ${TRAVIS_BRANCH}

#deploy:
#  file: dist/${SRC_TGZ}
#  provider: releases
#  skip_cleanup: true
#  # overwrite: true
#  on:
#    tags: true
#    all_branches: true
#    repo: phlummox/bogocopy
#  api_key:
#    secure: XXXX

