
image:
- Visual Studio 2019

cache:
- "c:\\Users\\appveyor\\AppData\\Local\\Programs\\stack"
- "c:\\Users\\appveyor\\AppData\\Roaming\\stack"

skip_commits:
  files:
    - .github/workflows/*
    - "*.md"
    - "*.pmd"

environment:
  matrix:
    - lts: lts-11
    - lts: lts-14

matrix:
  fast_finish: false

before_build:
- choco install haskell-stack
- choco install make
- choco install gnuwin32-coreutils.install --version 5.3.0
- stack build --stack-yaml=stack-%lts%.yaml --test --dry-run --dependencies-only
- stack build --stack-yaml=stack-%lts%.yaml --test --no-run-tests --fast --dependencies-only
# high cache compression
- ps: $env:APPVEYOR_CACHE_ENTRY_ZIP_ARGS = "-t7z -m0=lzma -mx=9"


build_script:
  - stack build --stack-yaml=stack-%lts%.yaml --fast

test_script:
  - stack build --stack-yaml=stack-%lts%.yaml --fast --test
  - "python --version"
  - docker version
  - make PLATFORM=Windows HUP_STACK_YAML=stack-%lts%.yaml clean docker-test

