cache:
- "c:\\sr -> appveyor.yml" ##
- "c:\\Users\\appveyor\\AppData\\Local\\Programs\\stack"

build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack --resolver=lts-11 setup > nul
- echo "" | stack --no-terminal --resolver lts-11 --stack-yaml stack-lts-11.yaml build
- echo "" | stack --no-terminal --resolver lts-11 --stack-yaml stack-lts-11.yaml test
- stack --resolver lts-11 --stack-yaml stack-lts-11.yaml exec -- hup --version
