
resolver: lts-7.14

packages:
- '.'
#- location:
#     git: https://github.com/phlummox/cmdargs
#     commit:  39e08514ad470c48c82cb42ef3987455c81727de
#  extra-dep: true

extra-deps: 
- http-client-0.5.5
- http-client-tls-0.3.3

# flags: {}

# to enable test code:
flags:
  hup:
#    PatchHelpMessage: true
    EnableTests: true

extra-package-dbs: []

