resolver: lts-7.24
#resolver: lts-3.7

packages:
- '.'
#- location:
#     git: https://github.com/phlummox/cmdargs
#     commit:  39e08514ad470c48c82cb42ef3987455c81727de
#  extra-dep: true

extra-deps:
 
## for lts-3.7
#- shelly-1.6.8.1
#- simple-0.11.1
#- simple-templates-0.8.0.1

# for lts-7.14
##- http-client-0.4.31.2
- http-client-0.5.5
- http-client-tls-0.3.3

# flags: {}

# to enable test code:
flags:
  hup: #{}
#    PatchHelpMessage: true
    EnableWebTests: true

extra-package-dbs: []

