
name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.pmd'
      - appveyor.yml
      - .gitignore
  push:
    paths-ignore:
      - '**.md'
      - '**.pmd'
      - appveyor.yml
      - .gitignore

jobs:
  cabal_build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        cabal: ["3.6"]
        ghc:
          - "8.2.2"
          - "8.6.5"
          # see <https://github.com/phlummox/hup/issues/7> --
          # more recent versions of GHC won't work (until
          # Shelly is fixed)

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        # oft-given path of ~/.cabal/store is WRONG on windows.
        # see https://markkarpov.com/post/github-actions-for-haskell-ci.html
        key: ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze*') }}-${{github.ref_name}}
        restore-keys: |
          ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze*') }}
          ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.ghc }}-cabal
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build --dependencies-only --reorder-goals --max-backjumps=-1 --minimize-conflict-set

    - name: Build
      run: |
        cabal v2-clean
        cabal v2-build  --reorder-goals --max-backjumps=-1 --minimize-conflict-set

    - name: Documentation
      run: |
        cabal v2-haddock

    - name: Tests
      run: |
        cabal v2-build --dependencies-only --enable-tests --enable-benchmarks --reorder-goals --max-backjumps=-1 --minimize-conflict-set --flags "EnableWebTests"
        cabal v2-install hspec-discover
        cabal v2-test --enable-tests --flags "EnableWebTests"

    - name: Freeze dependencies
      shell: bash
      run: |
        cabal v2-freeze --enable-tests --enable-benchmarks --reorder-goals --max-backjumps=-1  --flags "EnableWebTests"
        mv cabal.project.freeze cabal.project.freeze.${{ runner.os }}-${{ matrix.ghc }}

    - name: Archive dependencies
      uses: actions/upload-artifact@v2
      with:
        name: cabal-project-freeze
        path: cabal.project.freeze.${{ runner.os }}-${{ matrix.ghc }}

    - name: Copy executable to cwd
      shell: bash
      run: |
        set -x
        export artifact_dir="binaries/hup-cabal-${{ runner.os }}-${{ matrix.ghc }}"
        mkdir -p "$artifact_dir"
        cabal v2-install --installdir="$artifact_dir" --install-method=copy

    - name: Archive executable
      uses: actions/upload-artifact@v2
      with:
        name: hup-binary
        path: binaries

  stack_build:
    name: ${{ matrix.os }}/ ${{ matrix.lts }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        # As at 2021-12-30:
        # - compiles and tests OK at least as far back as lts-3.22 (2016-01-10),
        #   using GHC 7.10.2, base 4.8.1.0, Cabal 1.22, stack 1.9.3
        # - note that lts >= 15 suffer from the same problem as GHC, above --
        #   see <https://github.com/phlummox/hup/issues/7>.
        lts: ["lts-11", "lts-14"]

    steps:
    - uses: actions/checkout@v2
      name: Check out code

     # takes about 15 min on mac
    - uses: phlummox-dev/actions-setup-docker@aeefd9ac1777ed7acbc8a2b88a8dbf7bd1de0b06
      # uses: docker-practice/actions-setup-docker@master
      # may be bug fixes after commit
      # e2e6958abd33da9808dbd96cbaf9b4f30b44011c
      if: runner.os == 'macOS'

    - name: check docker
      if: runner.os != 'Windows'
      run: |
        set -x
        docker version
        docker run --rm hello-world

    - name: install libvirt, gmake, coreutils
      shell: bash
      run: |
        set -x
        case ${{ runner.os }} in

          Linux)
            sudo apt-get update && sudo apt-get install -y make coreutils
            ;;

          macOS)
            # GNU make is already installed
            brew install coreutils
            # prob won't actually use libvirt, but meh
            brew install qemu gcc libvirt
            # qemu security not supported on mac:
            # https://www.naut.ca/blog/2020/08/26/ubuntu-vm-on-macos-with-libvirt-qemu/
            echo 'security_driver = "none"' >> /usr/local/etc/libvirt/qemu.conf
            echo "dynamic_ownership = 0" >> /usr/local/etc/libvirt/qemu.conf
            echo "remember_owner = 0" >> /usr/local/etc/libvirt/qemu.conf
            brew services start libvirt
            qemu-system-x86_64 --version
            ;;

          Windows)
            choco install make
            choco install gnuwin32-coreutils.install --version 5.3.0
            # pin the version of qemu installed, since more recent
            # ones seem buggy: see e.g.
            # <https://github.com/rust-osdev/bootloader/commit/2efd8824223234bcaf83180207cce6aebec9c45a>
            #choco install qemu --version 2021.5.5
            # echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            # test w:/ run: qemu-system-x86_64 --version
            ;;

          *)
            printf >&2 'Unrecognized OS'
            false
            ;;
        esac

        make --version
        sha256sum --version

    - uses: haskell/actions/setup@v1.2
      name: Setup Stack
      id: setup-haskell-stack
      with:
        ghc-version: "8.6.5"
        cabal-version: "3.6"
        enable-stack: true
        stack-version: "latest"

    - uses: actions/cache@v2
      name: Cache ~/.stack
      if: runner.os != 'Windows'
      with:
        key: ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.lts }}-stack-${{ hashFiles('stack-*yaml.lock') }}
        restore-keys: |
          ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.lts }}-stack
        path: |
          ${{ steps.setup-haskell-stack.outputs.stack-root }}

    # On Windows, some of the stack state (e.g. copies of GHC) is stored,
    # not in c:\sr, but in %LOCALAPPDATA%\Programs\stack
    # (e.g. C:\Users\runneradmin\AppData\Local\Programs\stack)
    - uses: actions/cache@v2
      name: Cache ~/.stack
      if: runner.os == 'windows'
      with:
        key: ${{ secrets.WINDOWS_CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.lts }}-stack-${{ hashFiles('stack-*yaml.lock') }}
        restore-keys: |
          ${{ secrets.WINDOWS_CI_CACHE_DATE }}-${{ runner.os }}-${{ matrix.lts }}-stack
        path: |
          ~\AppData\Local\Programs\stack
          ${{ steps.setup-haskell-stack.outputs.stack-root }}

    # see https://github.com/phlummox/hup/issues/8
    # On macOS, restoring cache may muck up executable permissions
    - name: Clear setup-exe-cache directory
      if: runner.os == 'macOS'
      run: rm -rf ${{ steps.setup-haskell-stack.outputs.stack-root }}/setup-exe-cache

    - name: Install dependencies
      run: |
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml --dry-run --dependencies-only
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml --fast --dependencies-only

    - name: Build
      run: |
        stack --stack-yaml=stack-${{ matrix.lts }}.yaml build

    - name: Test
      shell: bash
      run: |
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml --dry-run \
              --test --dependencies-only \
              --flag hup:EnableWebTests --flag hup:BuildStackBasedTests
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml \
              --test --dependencies-only --no-run-tests \
              --flag hup:EnableWebTests --flag hup:BuildStackBasedTests
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml \
              --test --no-run-tests \
              --flag hup:EnableWebTests --flag hup:BuildStackBasedTests
        stack build --stack-yaml=stack-${{ matrix.lts }}.yaml \
              --test \
              --flag hup:EnableWebTests --flag hup:BuildStackBasedTests

    - name: docker test
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -x

        make PLATFORM=${{ runner.os }} HUP_STACK_YAML=stack-${{ matrix.lts }}.yaml \
          clean docker-test

    - name: Copy executable to cwd
      shell: bash
      run: |
        set -x
        export artifact_dir="binaries/hup-stack-${{ runner.os }}-${{ matrix.lts }}"
        mkdir -p "$artifact_dir"
        stack --stack-yaml=stack-${{ matrix.lts }}.yaml --local-bin-path "$artifact_dir" \
          build --copy-bins

    - name: Archive executable
      uses: actions/upload-artifact@v2
      with:
        name: hup-binary
        path: binaries

  stack_static_build:
    name: linux static link
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: install libvirt, gmake, coreutils
      shell: bash
      run: |
        set -x
        sudo apt-get update && sudo apt-get install -y make coreutils

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        key: ${{ secrets.CI_CACHE_DATE }}-${{ runner.os }}-stack-static
        path: |
          .stack-static-root

    - name: check docker
      run: |
        set -x
        docker version
        docker run --rm hello-world

    - name: Build
      run: |
        make static-binaries/hup

    - name: Archive executable
      uses: actions/upload-artifact@v2
      with:
        name: hup-static-binary
        path: static-binaries

    - name: create release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        set -x

        # prepare file
        ref_name='${{github.ref_name}}'
        version="${ref_name:1}" # strip leading 'v'
        tar cvf hup-${version}-linux-amd64.tar.xz --xz -C static-binaries hup

        # download github-release tool
        curl -L 'https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2' | bunzip2 > github-release
        chmod a+rx ./github-release

        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        IFS='/' read repo_user repo_name  <<<$(echo "${{github.repository}}")

        ./github-release release \
            --user $repo_user \
            --repo $repo_name \
            --tag ${{github.ref_name}} \
            --name "Version $version" \
            --description "See the changelog for a detailed list of changes" \
            --draft

        ./github-release upload \
            --user $repo_user \
            --repo $repo_name \
            --tag ${{github.ref_name}} \
            --label "hup-${version}-linux-amd64.tar.xz" \
            --name "hup-${version}-linux-amd64.tar.xz" \
            --replace \
            --file "hup-${version}-linux-amd64.tar.xz"

