
name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  cabal_build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        cabal: ["3.6"]
        ghc:
          #- "8.2.2" # re-enable this in public repo
          - "8.6.5"
          # SEE <GIVE_BUG_NUM_HERE> re workable ghc versions

    steps:
    - uses: actions/checkout@v2
      name: Check out code


